Add config file for pre-commit utility
klochenok/Django_blog pull request #1
Opened 2016-12-01 12:18 UTC by klochenok

Add config file with pre-commit hooks which allow automatically point out issues and fix trivial errors before code review.

2016-12-01 12:30 UTC, webknjaz requested changes
According to this branch name you are integrating the TravisCI checks into the repo. So please:
1) [X] Adjust PR title and description accrodingly
2) [X] Go to travis-ci.org and enable this repo there. (Hint: you may want to tick a checkbox in settings, so it would run build only if there's `.travis.yml` in the repo)
3) [X] Add `.travis.yml` to this branch.

2016-12-01 12:30 UTC, webknjaz commented on .pre-commit-config.yaml
> +    - '--django'
Please remove quotes

2016-12-01 12:30 UTC, webknjaz commented on .pre-commit-config.yaml
> +
Please remove one line.

2016-12-01 12:30 UTC, webknjaz commented on mysite/local_settings.py
> +import os
This file is committed by mistake. `git rm --cached mysite/local_settings.py; echo 'local_settings.py' >> .gitignore; git add .gitignore` would fix this.

2016-12-01 12:30 UTC, webknjaz commented on mysite/settings.py
> +<<<<<<< HEAD
Please learn about merge conflict markers and fix this module accordingly. (You have to pick what to keep in this module and what to wipe out).
Also please run `pre-commit install` to enable pre-commit tool do checks automatically in the local repo.

2016-12-01 22:07 UTC, webknjaz requested changes
Please fix all issues I stated. Also it would be better to name this PR `Configure Travis CI to run pre-commit checks`

2016-12-01 22:07 UTC, webknjaz commented on .gitignore
> +.DS_Storelocal_settings.py
It's a typo which has to be separated.

2016-12-01 22:07 UTC, webknjaz commented on mysite/settings.py
> +<<<<<<< HEAD
this is still not fixed

2016-12-06 06:56 UTC, webknjaz commented
@klochenok any update?

2016-12-06 18:22 UTC, webknjaz commented on mysite/settings.py
> -    from .local_settings import *
Why did you remove this version instead of leaving it here?

2016-12-06 18:39 UTC, klochenok commented on mysite/settings.py
> -    from .local_settings import *
I think that it's a solution of merge conflict.

2016-12-06 19:52 UTC, webknjaz commented on mysite/settings.py
> -    from .local_settings import *
It is one of the solutions for the merge. But is it really what you need? According to the tutorial, you the code you removed.

2016-12-06 21:51 UTC, webknjaz approved these changes

2016-12-08 10:05 UTC, merged