Configure automatic deployment to Heroku
klochenok/Django_blog pull request #4
Opened 2016-12-29 21:37 UTC by klochenok

This PR describes steps of deploying app on Heroku by creating specific files and settings. This repo has been also activated for automatic deployment on Heroku.

2016-12-29 22:09 UTC, webknjaz requested changes
Re-open the issue to do things right. Merging the PR should automatically close it.

2016-12-29 22:09 UTC, webknjaz commented on .gitignore
> +
This line is useless

2016-12-29 22:09 UTC, webknjaz commented on mysite/settings.py
> -
I'd add a separator line here

2016-12-29 22:09 UTC, webknjaz commented on mysite/settings.py
>      'default': {
Please find and fulfill my comment about dj_database_url

2016-12-29 22:09 UTC, webknjaz commented on dev-requirements.txt
> +-r requirements.txt
dev-only requirements must be moved here.

2016-12-29 22:23 UTC, klochenok commented on mysite/settings.py
>      'default': {
As I understand you mean to put here `import dj_database_url`?

2016-12-30 08:35 UTC, webknjaz commented on mysite/settings.py
>      'default': {
No, the config retrieval

2017-01-23 21:38 UTC, webknjaz requested changes

2017-01-23 21:38 UTC, webknjaz commented on mysite/wsgi.py
>  os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')
According to doc whitenoise import should go next to this line

2017-01-26 18:27 UTC, webknjaz commented on .pre-commit-config.yaml
> +    exclude: blog/migrations/
Do you have any trailing whitespaces errors for this folder?

2017-01-26 18:28 UTC, webknjaz commented on .pre-commit-config.yaml
> +#- repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
I think this is wrong

2017-01-26 18:32 UTC, webknjaz commented on requirements/test.txt
> +pre-commit==0.9.4
Upgrade to 0.10.1+

2017-01-26 22:56 UTC, klochenok commented on .pre-commit-config.yaml
> +    exclude: blog/migrations/
I have too long line error, it even doesn't get into "max-line-length" interval.

2017-01-26 23:08 UTC, klochenok commented on .pre-commit-config.yaml
> +#- repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
Agree, but I delayed fixing these errors. I had had this variant before we rebased branch, but this commit was lost.

2017-01-27 10:41 UTC, pavlenk0 approved these changes

2017-01-27 10:53 UTC, webknjaz commented on .pre-commit-config.yaml
> +    exclude: blog/migrations/
what do long lines have to do with trailing whitespaces hook?

2017-01-27 10:54 UTC, webknjaz commented on mysite/wsgi.py
> -
Why did you remove the separation between stdlib packages and installed ones?

2017-01-27 11:24 UTC, klochenok commented on mysite/wsgi.py
> -
Fixed it

2017-01-27 11:53 UTC, webknjaz approved these changes

2017-01-27 12:58 UTC, merged