Add vagga integration (sqlite version)
klochenok/Django_blog pull request #8
Opened 2017-02-17 20:13 UTC by klochenok

Integrate with vagga #5

2017-02-17 20:30 UTC, DrEdi requested changes
Fix versions of deps, please.

2017-02-17 20:30 UTC, DrEdi commented on vagga.yaml
> +      - 'gunicorn >=19.6.0, <20.0'
You can write just 19.6

2017-02-17 20:30 UTC, DrEdi commented on vagga.yaml
> +      - 'django-environ >=0.4.1, <1.0'
Here also better to leave just to the minor version.
Read very good article about this [here](http://semver.org/#semantic-versioning-200)

2017-02-18 03:33 UTC, webknjaz requested changes

2017-02-18 03:33 UTC, webknjaz commented on vagga.yaml
> +  django:
It would be nice to have `environ-file` in this container declaration

2017-02-18 03:33 UTC, webknjaz commented on vagga.yaml
> +    - !Sh pip freeze > requirements.txt
Keep this file the same as it is now (including other files)

2017-02-18 03:33 UTC, webknjaz commented on vagga.yaml
> +  run: !command
Have you tested this?

2017-02-18 03:33 UTC, webknjaz commented on vagga.yaml
> +  manage.py:
and this?

2017-02-20 10:21 UTC, klochenok commented on vagga.yaml
> +    - !Sh pip freeze > requirements.txt
Do you mean to divide requirements file like i did it before?

2017-02-20 10:39 UTC, webknjaz commented on vagga.yaml
> +    - !Sh pip freeze > requirements.txt
yes

2017-02-21 17:09 UTC, MaxymVlasov commented on .gitignore
> +.vagga
I need newline at end of file.
Give me it)

2017-02-25 21:05 UTC, DrEdi approved these changes

2017-02-25 22:00 UTC, webknjaz requested changes
Check yourself first before submitting for review

2017-02-25 22:00 UTC, webknjaz commented on vagga.yaml
> +    - !Sh pip uninstall -r requirements/common.txt
I guess you are missing `--yes` here

2017-02-25 22:58 UTC, webknjaz approved these changes

2017-02-25 23:06 UTC, pavlenk0 approved these changes

2017-02-25 23:55 UTC, merged